### PR TITLE
edit(IDP-1539): Updated extension apply command after breaking change…

### PR DESCRIPTION
**Pull request by MIA-Deltat1995**
## What this PR is for?

Updated extension apply command after breaking changes on request body schema

### CODE REVIEW

**Review by fredmaggiowski — APPROVED** [review]
LGTM

**Review by fredmaggiowski — APPROVED** [review]
LGTM

**Review by ThisIsDemetrio — APPROVED** [review]
LGTM

**Comment by fredmaggiowski** [comment]
This must land on main before thursday

**Review by JGiola — APPROVED** [review]

**Pull request merged**
