### PR TITLE
changing import in main.go for fixing issue #1

### LINKED ISSUE #1: miactl installation
On Mac 10.15.2, go version go1.14.2 darwin/amd64 the installation of miactl fails

`go get -u github.com/mia-platform/miactl
unrecognized import path "miactl/cmd": import path does not begin with hostname` 

I think that main.go should include

`import "cmd"`

### PR DESCRIPTION
**Pull request by giulioroggero**
Install via

`go get -u github.com/mia-platform/miactl`

doesn't works.

This pull request should Fixes #1 issue.

### CODE REVIEW

**Comment by giulioroggero** [comment]
I tried but go package management is still something obscure for me if you want to install from github. :-)

**Comment by giulioroggero** [comment]
Bravo @davidebianchi !

I was not sure that it is needed to hardcode gitlab in all files. Go it's a little bit strange. I'm going to create the installer for brew and linux

**Comment by davidebianchi** [comment]
No, I don't think this is correct. I should see how to import local dependency, as of now in this branch you could try the cli, but I want to fix this in a better way

**Comment by davidebianchi** [comment]
After some digging, I found a method of go modules to use the relative path: [replace](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive).

But, if we use this method the requirement is that every sub package has a `go.mod` file, so every submodule will be a separated module from the project. 

As of now I prefer to maintain the implementation of this PR, but we could decide later to use the replace directive.

**Pull request merged**
